index:
  path: /
  controller: App\Controller\IndexController::index

search-city:
  path: /search-city
  controller: App\Controller\IndexController::searchCity

convert:
  path: /convert
  controller: App\Controller\IndexController::convert

convert-history:
  path: /convert-history
  controller: App\Controller\ConvertHistoryController::index
